version: '3.4'

networks:
    api:

services:
  db:
    container_name: forum-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433 
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=password123!
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &

      until /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'password123!' -Q 'SELECT 1' &> /dev/null; do
        >&2 echo '>>>>>>>>>> SQL Server is unavailable - sleeping <<<<<<<<<<';
        sleep 5;
      done;
      echo '>>>>>>>>>> SQL Server is ready - executing init script <<<<<<<<<<';
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'password123!' -d master -i /tmp/mssql-init.sql;

      sleep infinity;"
    volumes:
      - ./db_creation.sql:/tmp/mssql-init.sql
    networks:
    - api

  api:
    container_name: forum-api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:80;https://+:443
    - ASPNETCORE_HTTPS_PORT=5000 
    - ASPNETCORE_HTTP_PORT=5001
    - DB_HOST=forumdb
    - DB_NAME=forumbackendapp
    - DB_SA_PASSWORD=password123!
    ports:
    - "5000:80"
    - "5001:443"
    depends_on:
    - db
    networks:
    - api